"use client";

import { useState } from "react";
import { Download, Check } from "lucide-react";
import { incrementCatalogueDownload } from "@/app/actions/catalogue";
import { Button } from "@/components/ui";

export function DownloadButton({ id, title }: { id: number; title: string }) {
  const [done, setDone] = useState(false);
  const handle = async () => {
    const blob = new Blob(
      [`ChromaShield — ${title}\n\nThis is a demo document generated by the QR Rewards platform.\nDocument ID: ${id}`],
      { type: "text/plain" },
    );
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/\s+/g, "-").toLowerCase()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    await incrementCatalogueDownload(id);
    setDone(true);
    setTimeout(() => setDone(false), 2500);
  };
  return (
    <Button variant={done ? "soft" : "outline"} className="w-full" onClick={handle}>
      {done ? <><Check className="h-4 w-4" /> Downloaded</> : <><Download className="h-4 w-4" /> Download</>}
    </Button>
  );
}
