"use client";

import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ScanLine, RotateCcw, CheckCircle2, AlertTriangle, Trophy } from "lucide-react";
import { useRouter } from "next/navigation";
import { Scanner as QrScanner } from "@yudiel/react-qr-scanner";
import { Button, Badge, Avatar } from "@/components/ui";
import { useToast } from "@/components/toast";
import { processRealScan } from "@/app/actions/scan";
import { cn, formatNumber } from "@/lib/utils";

type State = "idle" | "scanning" | "success" | "duplicate" | "unavailable" | "error";

type Result =
  | {
      outcome: "success";
      product: { name: string; imageUrl: string | null };
      points: number;
      multiplier: number;
      newBalance: number;
      newTier: string;
    }
  | null;

export function Scanner({ userId }: { userId: number }) {
  const [state, setState] = useState<State>("idle");
  const [result, setResult] = useState<Result>(null);
  const router = useRouter();
  const { toast } = useToast();

  const handleScan = async (detectedCodes: any[]) => {
    if (state !== "scanning") return;
    
    const detectedCode = detectedCodes[0];
    if (!detectedCode || !detectedCode.rawValue) return;
    
    const rawValue = detectedCode.rawValue;
    setState("idle"); // Pause scanning

    try {
      let codeToProcess = rawValue;

      // Ensure the QR code is generated by our platform
      if (rawValue.includes("/s/")) {
        const parts = rawValue.split("/s/");
        codeToProcess = parts[parts.length - 1];
      } else if (!/^[A-Za-z0-9_-]{8,20}$/.test(rawValue)) {
        // Simple sanity check, if it's not a valid code format
        toast({ tone: "error", title: "Invalid QR Code", description: "This QR code does not belong to our platform." });
        setState("error");
        return;
      }

      const res = await processRealScan(userId, codeToProcess);

      if (!res.ok) {
        if (res.reason === "already_redeemed") {
          setState("duplicate");
          toast({ tone: "warning", title: "Already redeemed", description: "This QR code was already used." });
        } else if (res.reason === "not_found") {
          setState("error");
          toast({ tone: "error", title: "Invalid QR Code", description: "This code was not found or is inactive." });
        } else {
          setState("error");
          toast({ tone: "error", title: "Error", description: res.message || "Could not process code." });
        }
        return;
      }

      setResult({
        outcome: "success",
        product: res.product as any, // Mapped in processRealScan
        points: res.points!,
        multiplier: res.multiplier!,
        newBalance: res.newBalance!,
        newTier: res.newTier!,
      });
      setState("success");
      toast({
        tone: "success",
        title: res.multiplier && res.multiplier > 1 ? "🎉 Bonus Points Earned!" : "⭐ Points Credited!",
        description: `+${res.points} points added to your wallet.`,
      });
      router.refresh();
      
    } catch (err) {
      toast({ tone: "error", title: "Error", description: "Failed to process scan." });
      setState("error");
    }
  };

  const start = () => {
    setState("scanning");
  };

  const reset = () => {
    setState("idle");
    setResult(null);
  };

  return (
    <div className="flex min-h-[640px] flex-col px-5 pb-8 pt-4">
      <h1 className="mb-1 text-xl font-bold tracking-tight text-content">Scan QR Code</h1>
      <p className="mb-5 text-sm text-muted">Point your camera at a product QR to authenticate & earn</p>

      <div className="relative mx-auto aspect-square w-full max-w-[300px]">
        <div className="absolute inset-0 overflow-hidden rounded-3xl border border-border bg-slate-900">
          <div className="absolute inset-0 opacity-30" style={{ backgroundImage: "radial-gradient(circle at 30% 40%, #4f46e5 0, transparent 50%), radial-gradient(circle at 70% 70%, #0ea5e9 0, transparent 50%)" }} />

          <AnimatePresence mode="wait">
            {state === "idle" && (
              <motion.div key="idle" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="flex h-full flex-col items-center justify-center gap-3 text-white/70">
                <ScanLine className="h-10 w-10" />
                <p className="text-xs">Ready to scan</p>
              </motion.div>
            )}

            {state === "scanning" && (
              <motion.div key="scanning" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="absolute inset-0 bg-black">
                <QrScanner
                  onScan={handleScan}
                  onError={(error) => {
                    console.error("Scanner error:", error);
                    toast({ tone: "error", title: "Camera Error", description: "Failed to access camera." });
                    setState("error");
                  }}
                  components={{
                    onOff: true,
                    torch: true,
                    zoom: true,
                    finder: true,
                  }}
                  styles={{
                    container: { width: '100%', height: '100%', borderRadius: '1.5rem' }
                  }}
                />
              </motion.div>
            )}

            {state === "success" && result?.outcome === "success" && (
              <motion.div key="success" initial={{ scale: 0.6, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} className="flex h-full flex-col items-center justify-center gap-2">
                <CoinBurst points={result.points} />
              </motion.div>
            )}

            {state === "duplicate" && (
              <motion.div key="dup" initial={{ scale: 0.6, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} className="flex h-full flex-col items-center justify-center gap-3 text-center">
                <div className="flex h-20 w-20 items-center justify-center rounded-full bg-amber-500/20">
                  <AlertTriangle className="h-10 w-10 text-amber-400" />
                </div>
                <p className="text-sm font-semibold text-white">Already Scanned</p>
                <p className="px-6 text-xs text-white/60">This code has already been used.</p>
              </motion.div>
            )}

            {state === "error" && (
              <motion.div key="err" initial={{ scale: 0.6, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} className="flex h-full flex-col items-center justify-center gap-3 text-center">
                <div className="flex h-20 w-20 items-center justify-center rounded-full bg-red-500/20">
                  <AlertTriangle className="h-10 w-10 text-red-400" />
                </div>
                <p className="text-sm font-semibold text-white">Invalid QR</p>
                <p className="px-6 text-xs text-white/60">This is not a valid platform QR code.</p>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>

      {/* Result card */}
      <AnimatePresence>
        {state === "success" && result?.outcome === "success" && (
          <motion.div initial={{ y: 30, opacity: 0 }} animate={{ y: 0, opacity: 1 }} className="mt-5 rounded-3xl border border-success/30 bg-success-soft p-5 text-center z-10">
            <CheckCircle2 className="mx-auto h-10 w-10 text-success" />
            <p className="mt-2 text-sm font-semibold text-content">Product Authenticated!</p>
            <div className="mt-3 flex items-center justify-center gap-3">
              <Avatar src={result.product.imageUrl} name={result.product.name} size={64} className="rounded-xl shadow-sm" fallbackIcon={<CheckCircle2 className="h-8 w-8 text-muted" />} />
              <div className="text-left">
                <p className="font-semibold text-content">{result.product.name}</p>
                <Badge tone="success">Genuine Product ✓</Badge>
              </div>
            </div>
            <div className="mt-4 rounded-2xl bg-white/60 p-3 dark:bg-black/20">
              <p className="text-xs text-muted">Reward Points Earned</p>
              <p className="flex items-center justify-center gap-1 text-3xl font-bold text-success">
                +{formatNumber(result.points)}
              </p>
              {result.multiplier > 1 && (
                <p className="mt-1 text-xs font-medium text-accent">🎆 2× Campaign Bonus applied!</p>
              )}
            </div>
            <div className="mt-3 flex items-center justify-center gap-1.5 rounded-xl bg-brand-soft px-3 py-2 text-xs text-brand">
              <Trophy className="h-3.5 w-3.5" /> New balance: {formatNumber(result.newBalance)} pts · {result.newTier} tier
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="mt-auto pt-6">
        {state === "idle" ? (
          <Button onClick={start} size="lg" className="w-full">
            <ScanLine className="h-5 w-5 mr-2" /> Start Camera
          </Button>
        ) : state === "scanning" ? (
          <Button onClick={reset} size="lg" variant="outline" className="w-full">
            Cancel
          </Button>
        ) : (
          <Button onClick={reset} size="lg" variant="outline" className="w-full">
            <RotateCcw className="h-5 w-5 mr-2" /> Scan Another
          </Button>
        )}
        <p className="mt-3 text-center text-xs text-subtle">
          🔒 Each scan authenticates a genuine product & credits real reward points
        </p>
      </div>
    </div>
  );
}

function CoinBurst({ points }: { points: number }) {
  const coins = Array.from({ length: 14 });
  return (
    <div className="relative">
      {coins.map((_, i) => {
        const angle = (i / coins.length) * Math.PI * 2;
        // eslint-disable-next-line react-hooks/purity
        const dist = 60 + Math.random() * 50;
        const x = Math.cos(angle) * dist;
        const y = Math.sin(angle) * dist;
        return (
          <motion.span
            key={i}
            className="absolute left-1/2 top-1/2 text-xl pointer-events-none"
            initial={{ x: 0, y: 0, opacity: 1, scale: 0.5 }}
            // eslint-disable-next-line react-hooks/purity
            animate={{ x, y, opacity: 0, scale: 1.2, rotate: Math.random() * 360 }}
            // eslint-disable-next-line react-hooks/purity
            transition={{ duration: 1.1, ease: "easeOut", delay: Math.random() * 0.15 }}
          >
            🪙
          </motion.span>
        );
      })}
      <motion.div
        className="flex h-24 w-24 items-center justify-center rounded-full bg-success text-white shadow-lg z-10 relative"
        initial={{ scale: 0 }}
        animate={{ scale: 1 }}
        transition={{ type: "spring", damping: 12 }}
      >
        <div className="text-center">
          <p className="text-[10px] font-medium opacity-80">YOU EARNED</p>
          <p className="text-2xl font-bold leading-none">+{points}</p>
        </div>
      </motion.div>
    </div>
  );
}
